version: '3'

services:
  frontend:
    container_name: frontend_kwickbit_v0
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    networks:
      - kwickbit-network
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_QUICKBOOK_CLIENT_ID=${NEXT_PUBLIC_API_QUICKBOOK_CLIENT_ID}
      - NEXT_PUBLIC_API_QUICKBOOK_CLIENT_SECRET=${NEXT_PUBLIC_API_QUICKBOOK_CLIENT_SECRET}
      - NEXT_PUBLIC_API_QUICKBOOK_REDIRECT_URI=${NEXT_PUBLIC_API_QUICKBOOK_REDIRECT_URI}
      - NEXT_PUBLIC_API_QUICKBOOK_SCOPE=${NEXT_PUBLIC_API_QUICKBOOK_SCOPE}
    volumes:
      - .:/app
      - /app/node_modules

networks:
  kwickbit-network:
    external:
      name: kwickbit_network