---
- name: Assume Role
  community.aws.sts_assume_role:
    role_arn: "{{ role_arn }}"
    role_session_name: "AnsibleSession"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: aws_assumed_role

- name: Upload file to S3 using assumed role credentials
  community.aws.s3_sync:
    bucket: "{{ bucket_to_upload }}"
    file_root: "{{ project_root_path }}/out/"
    mode: push
    access_key: "{{ aws_assumed_role.sts_creds.access_key }}"
    secret_key: "{{ aws_assumed_role.sts_creds.secret_key }}"
    session_token: "{{ aws_assumed_role.sts_creds.session_token }}"
    region: "{{ aws_region }}"