---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    project_root_path: "{{ (playbook_dir + '/../../..') | realpath }}"
  roles:
    - role: copy_env_file
      vars:
        env_file_path: "{{ project_root_path}}/deploy/ansible/inventories/{{ project_env }}/resources/.env.production.{{ project_env }}"
    - role: project_build
    - role: aws_upload
    - role: invalidate_cloudfront_distribution
