---
- name: Assume Role
  community.aws.sts_assume_role:
    role_arn: "{{ role_arn }}"
    role_session_name: "AnsibleSession"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: aws_assumed_role

- name: Invalidate Cloudfront distribution
  community.aws.cloudfront_invalidation:
    distribution_id: "{{ cloudfront_distribution_id }}"
    target_paths:
      - "/*"
    aws_access_key: "{{ aws_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ aws_assumed_role.sts_creds.secret_key }}"
    session_token: "{{ aws_assumed_role.sts_creds.session_token }}"