---
- name: Build project
  command: "npm run build"
  args:
    chdir: "{{ project_root_path }}"
- name: Export project files
  command: "npm run export"
  args:
    chdir: "{{ project_root_path }}"
